version: '3'
services:
  postgresql:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=123456

  redis:
    image: 'redis:latest'

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /home/app/node_modules
      - ./server:/home/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6374
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=123456
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /home/app/node_modules
    - ./client:/home/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/app/node_modules
      - ./worker:/home/app
